# Naive Bayes Tutorial Part 1: Predicting survival from titanic crash

In [53]:
import pandas as pd

df = pd.read_csv(r"/kaggle/input/test-file/tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# NAive

In [54]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [55]:
df.shape

(418, 5)

In [56]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [57]:
inputs

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

     Pclass     Sex   Age      Fare
0         3    male  34.5    7.8292
1         3  female  47.0    7.0000
2         2    male  62.0    9.6875
3         3    male  27.0    8.6625
4         3  female  22.0   12.2875
..      ...     ...   ...       ...
413       3    male   NaN    8.0500
414       1  female  39.0  108.9000
415       3    male  38.5    7.2500
416       3    male   NaN    8.0500
417       3    male   NaN   22.3583

[418 rows x 4 columns]

In [58]:
inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})
inputs

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

     Pclass  Sex   Age      Fare
0         3    1  34.5    7.8292
1         3    2  47.0    7.0000
2         2    1  62.0    9.6875
3         3    1  27.0    8.6625
4         3    2  22.0   12.2875
..      ...  ...   ...       ...
413       3    1   NaN    8.0500
414       1    2  39.0  108.9000
415       3    1  38.5    7.2500
416       3    1   NaN    8.0500
417       3    1   NaN   22.3583

[418 rows x 4 columns]

In [59]:
inputs.isnull().sum()

Pclass     0
Sex        0
Age       86
Fare       1
dtype: int64

In [60]:
inputs.Age[:10]

0    34.5
1    47.0
2    62.0
3    27.0
4    22.0
5    14.0
6    30.0
7    26.0
8    18.0
9    21.0
Name: Age, dtype: float64

In [61]:

inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  34.5   7.8292
1       3    2  47.0   7.0000
2       2    1  62.0   9.6875
3       3    1  27.0   8.6625
4       3    2  22.0  12.2875

In [62]:
inputs.Fare = inputs.Fare.fillna(inputs.Fare.mean())
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  34.5   7.8292
1       3    2  47.0   7.0000
2       2    1  62.0   9.6875
3       3    1  27.0   8.6625
4       3    2  22.0  12.2875

In [63]:
inputs.shape

(418, 4)

In [64]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [65]:
target

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [67]:
X_train.shape

(334, 4)

In [68]:
X_test.shape

(84, 4)

In [69]:
X_test

     Pclass  Sex    Age      Fare
403       1    1  17.00   47.1000
331       1    1  39.00   29.7000
337       3    1  39.00    7.2292
307       3    1   0.83    9.3500
254       3    1  32.50    9.5000
..      ...  ...    ...       ...
180       2    1  30.00   13.0000
381       3    1  26.00    7.8792
1         3    2  47.00    7.0000
112       1    2  36.00   31.6792
59        1    2  36.00  262.3750

[84 rows x 4 columns]

In [70]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() ## when data-distribution is Normal

In [71]:

model.fit(X_train,y_train)

GaussianNB()

In [72]:
model.score(X_test,y_test)

1.0

In [73]:

X_test[0:10]

     Pclass  Sex       Age      Fare
403       1    1  17.00000   47.1000
331       1    1  39.00000   29.7000
337       3    1  39.00000    7.2292
307       3    1   0.83000    9.3500
254       3    1  32.50000    9.5000
306       1    1  30.00000  151.5500
327       1    1  46.00000   79.2000
53        1    2  28.00000  263.0000
380       3    1  30.27259    7.7500
47        3    1  30.27259    7.7500

In [74]:
# comparing wuth y_test
y_test[0:10]

403    0
331    0
337    0
307    0
254    0
306    0
327    0
53     1
380    0
47     0
Name: Survived, dtype: int64

In [75]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

# Email SPAm / Ham detection

In [10]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ASUS\ML practice\spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [14]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.25)

In [20]:
df.shape

(5572, 3)

***Using Count Vectorizer to make Matrix of unique words in the corpus***

In [22]:
## Using Count Vectorizer to make Matrix of unique words in the corpus
# here. corpus means the whole dataset,row means the total unique words present
# column is the total document present
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [29]:
# Demo

In [31]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [33]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9885139985642498

In [ ]:
## here to transform the words we use count vectorizer
# for more transformation can use TF-IDF

#  Sklearn Pipeline

In [44]:
## writing the same code using Simple Api
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [46]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [48]:
clf.score(X_test,y_test)

0.9885139985642498

In [50]:

clf.predict(emails)

array([0, 1], dtype=int64)

# Machine Learning Tutorial - Naive Bayes: Exercise
Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [26]:
from sklearn.datasets import load_wine
import pandas as pd

# Load the dataset
wine = load_wine()


# Convert to DataFrame
df = pd.DataFrame(wine.data, columns=wine.feature_names)

# Add target column
df['target'] = wine.target

# Preview the first 5 rows
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [14]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [28]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [16]:
inputs = df.drop('target',axis='columns')
target = df.target

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.25)

In [20]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9777777777777777

In [24]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.8222222222222222